<?php

/**
 * @file
 * Spotify related hooks
 */
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\node\NodeInterface;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\node\Entity\Node;
use Drupal\taxonomy\Entity\Term;


/**
 * Implements hook_page_attachments().
 */
function spotifytest_page_attachments(array &$page) {
  if (!\Drupal::currentUser()->hasPermission('access contextual links')) {
    return;
  }

  $page['#attached']['library'][] = 'spotifytest/drupal.spotifytest';
}

/**
 * Implements hook_theme().
 */
function spotifytest_theme($existing, $type, $theme, $path) {
  return [
    'spotifytest_artistslist_block' => [
      'variables' => [
        'nodes_build' => [],
      ],
      'template'  => 'spotifytest-artistslist-block',
    ],
  ];
}


/**
 * @} End of "defgroup hooks_example".
 */
