<?php

/**
 * @file
 * Spotify related hooks
 */

/**
 * Implements hook_page_attachments().
 */
function spotifytest_page_attachments(array &$page) {
  if (!\Drupal::currentUser()->hasPermission('access contextual links')) {
    return;
  }

  $page['#attached']['library'][] = 'spotifytest/drupal.spotifytest';
}

/**
 * Implements hook_theme().
 */
function spotifytest_theme($existing, $type, $theme, $path) {
  return [
    'spotifytest_artistslist_block' => [
      'variables' => [
        'nodes_build' => [],
      ],
      'template'  => 'spotifytest-artistslist-block',
    ],
    'spotifytest_artist_page' => [
      'variables' => [
        'artist' => [],
      ],
      'template'  => 'spotifytest-artist-page',
    ],
  ];
}
